### PR TITLE
Feature/to sbn from v01 00 12

### PR DESCRIPTION
**Pull request by jedori0228**
This PR includes
- Enables GENIE3
  - I haven't tested this on GENIE2, but probably won't work. Should we detect GENIE version, and make an exception when it's <3?
- For some of the GENIE+ systematics, return 1.-filled weight vector when they are not applicable, rather than a empty one (uses function defined in https://github.com/LArSoft/systematicstools/pull/1)

### CODE REVIEW

**Comment by lgarren** [comment]
@jedori0228 There is no longer any need to support genie v2.

**Comment by knoepfel** [comment]
We have placed this PR in draft state.  We would like to have a design discussion with you.  Please contact scisoft-team@fnal.gov at your convenience.

**Comment by jedori0228** [comment]
ICARUS-specific files are now removed.

**Comment by lgarren** [comment]
DUNE unit tests are OK.  That may be the best we can do for now.

**Comment by lgarren** [comment]
approve

**Pull request merged**
